githubApi:
  baseUrl: https://api.github.com

timeout:
  connection: 1000
  read: 1000

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 5
        waitDuration: 100ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException.NotFound
          - org.springframework.web.client.HttpClientErrorException.BadRequest
